import { Product } from "@/types/product";

export const collections = [
  {
    id: 1,
    name: "Huy Hiệu Thạch Âm (vàng)",
    description: "",
    image: "/products/yellow-badge-transparent.png",
  },
  {
    id: 2,
    name: "Khăn Bandana Thạch Âm",
    description: "",
    image: "/products/bandana-transparent.png",
  },

  {
    id: 3,
    name: "Quạt Giấy Thạch Âm - Khmer Wind",
    description: "",
    image: "/products/hand-fan-1-transparent.png",
  },
  {
    id: 4,
    name: "Quạt Giấy Thạch Âm - Naga Wind",
    description: "",
    image: "/products/hand-fan-2-transparent.png",
  },
  {
    id: 5,
    name: "Bình Gốm Di Sản - Naga Hoa",
    description: "",
    image: "/products/ceramic-vase-transparent.png",
  },
  {
    id: 6,
    name: "Ly Gốm Thạch Âm - Naga Tịnh Ấm",
    description: "",
    image: "/products/ceramic-glass-transparent.jpeg",
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Huy Hiệu Thạch Âm - Xanh Rêu",
    images: ["/products/green-badge.png", "/products/green-badge.jpg"],
    background: "linear-gradient(to right, #e5e5e5, #e9e9e9, #eee)",
    zoom: [],
    descriptionKey: "huy-hieu-thach-am-xanh-reu",
    code: "A001_693564536",
    brand: "Thạch Âm",
    material: "Kim loại mạ bóng, in hình phủ nhựa bóng/mờ",
    pin: "Ghim kim cài lưng (an toàn, dễ sử dụng)",
    category: "Huy hiệu",
    details: [
      {
        color: "Nền xanh rêu",
        slug: "huy-hieu-thach-am-xanh-reu",
        price: 20000,
        badge: {
          isNew: true,
          discount: 20,
        },
      },
      {
        color: "Nền vàng nhạt",
        slug: "huy-hieu-thach-am-vang-nhat",
        price: 20000,
        badge: {
          isNew: true,
          discount: 20,
        },
      },
    ],
    size: "10 cm",
    quantity: 8800,
    rating: [25, 50, 70, 500, 800],
  },
  {
    id: 2,
    name: "Huy Hiệu Thạch Âm - Vàng Nhạt",
    images: ["/products/yellow-badge.jpeg", "/products/yellow-badge.png"],
    background: "linear-gradient(to right, #e3e3e5, #e7e7e7, #eaeaea)",
    zoom: [],
    descriptionKey: "huy-hieu-thach-am-vang-nhat",
    code: "A001_693564596",
    brand: "Thạch Âm",
    material: "Kim loại mạ bóng, in hình phủ nhựa bóng/mờ",
    pin: "Ghim kim cài lưng (an toàn, dễ sử dụng)",
    category: "Huy hiệu",
    details: [
      {
        color: "Nền vàng",
        slug: "huy-hieu-thach-am-vang-nhat",
        price: 20000,
        badge: {
          isNew: true,
          discount: 20,
        },
      },
      {
        color: "Nền xanh rêu",
        slug: "huy-hieu-thach-am-xanh-reu",
        price: 20000,
        badge: {
          isNew: true,
          discount: 20,
        },
      },
    ],
    size: "10 cm",
    quantity: 7500,
    rating: [20, 40, 60, 400, 900],
  },
  {
    id: 3,
    name: "Khăn Bandana Thạch Âm",
    images: ["/products/bandana.png"],
    background: "linear-gradient(to right, #ebebeb, #eee, #ebebeb)",
    zoom: [],
    descriptionKey: "khan-bandana-thach-am",
    instructionKey: "khan-bandana-thach-am",
    code: "A001_694535520",
    brand: "Thạch Âm",
    material: "Lụa cao cấp",
    category: "Khăn",
    details: [
      {
        color: "Xanh rêu đậm",
        slug: "khan-bandana-thach-am",
        price: 255000,
        badge: {
          isNew: true,
          discount: 15,
        },
      },
    ],
    size: "70 cm × 70 cm",
    quantity: 6000,
    rating: [15, 25, 50, 320, 900],
  },
  {
    id: 4,
    name: "Card Visit Thạch Âm",
    images: ["/products/card-1.jpeg", "/products/card-2.png"],
    background: "#797979",
    zoom: [2, 3],
    descriptionKey: "card-visit-thach-am",
    code: "A001_01134034503",
    brand: "Thạch Âm",
    material: "Giấy mỹ thuật cao cấp",
    category: "Card",
    details: [
      {
        color: "Xanh rêu đậm & vàng đồng",
        slug: "card-visit-thach-am",
        price: 0,
        badge: {
          isNew: true,
          isReward: true,
        },
      },
    ],
    size: "90 mm × 54 mm",
    quantity: 9200,
    rating: [4, 8, 12, 190, 1256],
  },
  {
    id: 5,
    name: "Quạt Tay Thạch Âm - Khmer Wind",
    images: ["/products/hand-fan-1.jpg"],
    background: "#FCFCFC",
    zoom: [],
    descriptionKey: "quat-tay-thach-am-khmer-wind",
    instructionKey: "quat-tay-thach-am-khmer-wind",
    noteKey: "quat-tay-thach-am-khmer-wind",
    code: "A001_01134034745",
    brand: "Thạch Âm",
    material: "Giấy cao cấp",
    category: "Quạt",
    details: [
      {
        color: "Xanh rêu đậm & vàng đồng",
        slug: "quat-tay-thach-am-khmer-wind",
        price: 120000,
        pattern: "Khmer Wind",
        badge: {
          isNew: true,
          discount: 20,
          isBestseller: true,
        },
      },
      {
        color: "Xanh rêu đậm & vàng đồng",
        slug: "quat-tay-thach-am-naga-wind",
        pattern: "Naga Wind",
        price: 120000,
        badge: {
          isNew: true,
          discount: 20,
          isBestseller: true,
        },
      },
    ],
    size: "30 cm × 50 cm",
    quantity: 3400,
    rating: [11, 19, 27, 93, 2350],
  },
  {
    id: 6,
    name: "Quạt Tay Thạch Âm - Naga Wind",
    images: ["/products/hand-fan-2.jpg"],
    background: "#FCFCFC",
    zoom: [],
    descriptionKey: "quat-tay-thach-am-naga-wind",
    instructionKey: "quat-tay-thach-am-naga-wind",
    noteKey: "quat-tay-thach-am-naga-wind",
    code: "A001_01134034766",
    brand: "Thạch Âm",
    material: "Giấy cao cấp",
    category: "Quạt",
    details: [
      {
        color: "Xanh rêu đậm & vàng đồng",
        slug: "quat-tay-thach-am-naga-wind",
        pattern: "Naga Wind",
        price: 120000,
        badge: {
          isNew: true,
          discount: 20,
          isBestseller: true,
        },
      },
      {
        color: "Xanh rêu đậm & vàng đồng",
        slug: "quat-tay-thach-am-khmer-wind",
        pattern: "Khmer Wind",
        price: 120000,
        badge: {
          isNew: true,
          discount: 20,
          isBestseller: true,
        },
      },
    ],
    size: "30 cm × 50 cm",
    quantity: 3400,
    rating: [11, 19, 27, 83, 2383],
  },
  {
    id: 7,
    name: "Naga Hoa – Bình gốm di sản",
    images: ["/products/ceramic-vase.jpeg"],
    background: "linear-gradient(to right, #ebebeb, #eee, #ebebeb)",
    zoom: [0],
    descriptionKey: "naga-hoa-binh-gom-di-san",
    instructionKey: "naga-hoa-binh-gom-di-san",
    maintenanceKey: "naga-hoa-binh-gom-di-san",
    code: "A001_694534520",
    brand: "Thạch Âm",
    material: "Gốm sứ cao cấp",
    category: "Bình",
    details: [
      {
        color: "Xanh rêu đậm",
        slug: "naga-hoa-binh-gom-di-san",
        price: 350000,
        badge: {
          isNew: true,
          discount: 30,
        },
      },
    ],
    size: "9.5 cm × 15.5 cm",
    quantity: 7000,
    rating: [16, 19, 33, 492, 6440],
  },
  {
    id: 8,
    name: "Naga Tịnh Ấm – Ly gốm Thạch Âm",
    images: ["/products/ceramic-glass.jpeg"],
    background: "linear-gradient(to right, #ebebeb, #eee, #ebebeb)",
    zoom: [0],
    descriptionKey: "naga-tinh-am-ly-gom-thach-am",
    instructionKey: "naga-tinh-am-ly-gom-thach-am",
    maintenanceKey: "naga-tinh-am-ly-gom-thach-am",
    code: "A001_694537520",
    brand: "Thạch Âm",
    material: "Gốm sứ cao cấp",
    category: "Ly",
    details: [
      {
        color: "Xanh rêu đậm",
        slug: "naga-tinh-am-ly-gom-thach-am",
        price: 150000,
        badge: {
          isNew: true,
          discount: 25,
        },
      },
    ],
    size: "8.5 cm × 10.5 cm",
    quantity: 6000,
    rating: [58, 62, 175, 605, 5100],
  },
  {
    id: 9,
    name: "Naga Tịnh Ấm - Đế ly Thạch Âm",
    images: ["/products/ceramic-coaster.jpeg"],
    background: "linear-gradient(to right, #ebebeb, #eee, #ebebeb)",
    zoom: [0],
    descriptionKey: "naga-tinh-am-de-ly-thach-am",
    instructionKey: "naga-tinh-am-de-ly-thach-am",
    maintenanceKey: "naga-tinh-am-de-ly-thach-am",
    code: "A001_694537590",
    brand: "Thạch Âm",
    material: "Gốm sứ cao cấp",
    category: "Phụ kiện",
    details: [
      {
        color: "Xanh rêu đậm",
        slug: "naga-tinh-am-de-ly-thach-am",
        price: 45000,
        badge: {
          isNew: true,
          discount: 10,
        },
      },
    ],
    size: "10.5 cm × 2 cm",
    quantity: 5000,
    rating: [48, 52, 155, 745, 4000],
  },
  {
    id: 10,
    name: "Thạch Âm Khmer Pure",
    images: ["/products/beverages.jpeg"],
    background: "linear-gradient(to right, #ebebeb, #eee, #ebebeb)",
    zoom: [],
    descriptionKey: "thach-am-khmer-pure",
    instructionKey: "thach-am-khmer-pure",
    maintenanceKey: "thach-am-khmer-pure",
    noteKey: "thach-am-khmer-pure",
    code: "A001_694537540",
    brand: "Thạch Âm",
    bottleMaterial: "Thủy tinh",
    category: "Thức uống",
    details: [
      {
        variantId: 1,
        color: "",
        slug: "thach-am-khmer-pure",
        ingredient: "100% nước mía ép",
        drink: "Mía ép",
        price: 45000,
        badge: {
          discount: 10,
          isBestseller: true,
        },
      },
      {
        variantId: 2,
        color: "",
        slug: "thach-am-khmer-pure",
        ingredient: "100% nước dừa tươi",
        drink: "Dừa tươi",
        price: 45000,
        badge: {
          discount: 10,
          isBestseller: true,
        },
      },
      {
        variantId: 3,
        color: "",
        slug: "thach-am-khmer-pure",
        ingredient: "100% nước từ trái dừa nước",
        drink: "Dừa nước",
        price: 45000,
        badge: {
          discount: 10,
          isBestseller: true,
        },
      },
    ],
    volume: "180 ml",
    quantity: 4385,
    rating: [58, 61, 135, 945, 3186],
  },
];
